In [39]:
import pandas as pd
from pathlib import Path
from sodapy import Socrata
import datetime

In [56]:
client = Socrata("data.austintexas.gov", app_token='PKsmnIpUcg9vRfMFeZoUZunC4')

In [44]:
execution_date = '2023-11-19'
start_date = '2023-11-19'

In [51]:
execution_date = '2023-11-20'
start_date = '2023-11-19'

In [54]:
if execution_date == start_date:
    results = client.get("9t4d-g238", where="DateTime <= '{}'".format(start_date), limit=1000000)
else:
    prior_execution_date = (datetime.datetime.strptime(execution_date, '%Y-%m-%d') - datetime.timedelta(days=1)).strftime('%Y-%m-%d')
    results = client.get("9t4d-g238", where="DateTime > '{}' AND DateTime <= '{}'".format(prior_execution_date, execution_date), limit=10000)

In [50]:
pd.DataFrame(results)

,animal_id,name,datetime,monthyear,date_of_birth,outcome_type,animal_type,sex_upon_outcome,age_upon_outcome,breed,color,outcome_subtype
0,A794011,Chunk,2019-05-08T18:20:00.000,2019-05-08T18:20:00.000,2017-05-02T00:00:00.000,Rto-Adopt,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White,NaN
1,A776359,Gizmo,2018-07-18T16:02:00.000,2018-07-18T16:02:00.000,2017-07-12T00:00:00.000,Adoption,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown,NaN
2,A821648,NaN,2020-08-16T11:38:00.000,2020-08-16T11:38:00.000,2019-08-16T00:00:00.000,Euthanasia,Other,Unknown,1 year,Raccoon,Gray,NaN
3,A720371,Moose,2016-02-13T17:59:00.000,2016-02-13T17:59:00.000,2015-10-08T00:00:00.000,Adoption,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff,NaN
4,A674754,NaN,2014-03-18T11:47:00.000,2014-03-18T11:47:00.000,2014-03-12T00:00:00.000,Transfer,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby,Partner
...,...,...,...,...,...,...,...,...,...,...,...,...
157142,A859974,*Lady Gaga,2022-08-16T11:42:00.000,2022-08-16T11:42:00.000,2012-06-21T00:00:00.000,Adoption,Cat,Spayed Female,10 years,Devon Rex,White,NaN
157143,A856973,*Suede,2022-06-11T15:39:00.000,2022-06-11T15:39:00.000,2021-05-10T00:00:00.000,Adoption,Cat,Spayed Female,1 year,Domestic Medium Hair,Blue,NaN
157144,A852036,Queen,2022-03-17T17:22:00.000,2022-03-17T17:22:00.000,2021-12-08T00:00:00.000,Adoption,Dog,Spayed Female,3 months,German Shepherd Mix,Brown/Black,NaN
157145,A852775,A852775,2022-05-18T14:13:00.000,2022-05-18T14:13:00.000,2022-01-31T00:00:00.000,Adoption,Cat,Spayed Female,3 months,Domestic Medium Hair Mix,Tortie,Foster
157146,A854626,A854626,2022-05-03T16:10:00.000,2022-05-03T16:10:00.000,2022-02-27T00:00:00.000,Adoption,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Orange Tabby,Foster

In [55]:
pd.DataFrame(results)

,animal_id,datetime,monthyear,date_of_birth,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color,name
0,A893305,2023-11-19T10:43:00.000,2023-11-19T10:43:00.000,2021-11-19T00:00:00.000,Euthanasia,Suffering,Cat,Intact Female,NULL,Domestic Shorthair,Calico/Calico,NaN
1,A889463,2023-11-19T10:47:00.000,2023-11-19T10:47:00.000,2023-08-12T00:00:00.000,Adoption,NaN,Cat,Neutered Male,3 months,Domestic Shorthair,Black/White,Akira
2,A892941,2023-11-19T11:00:00.000,2023-11-19T11:00:00.000,2020-11-13T00:00:00.000,Adoption,NaN,Cat,Neutered Male,3 years,Snowshoe,Seal Point/White,*Kodiak
3,A893088,2023-11-19T11:30:00.000,2023-11-19T11:30:00.000,2011-11-15T00:00:00.000,Adoption,Foster,Dog,Neutered Male,12 years,Miniature Schnauzer,Buff/Cream,NaN
4,A893211,2023-11-19T11:49:00.000,2023-11-19T11:49:00.000,2012-11-17T00:00:00.000,Adoption,NaN,Dog,Spayed Female,11 years,Chow Chow,Cream,Chowbella
5,A893306,2023-11-19T12:27:00.000,2023-11-19T12:27:00.000,2013-11-19T00:00:00.000,Euthanasia,Suffering,Cat,Intact Female,NULL,Domestic Shorthair,Brown Tabby/White,NaN
6,A893191,2023-11-19T12:37:00.000,2023-11-19T12:37:00.000,2022-11-16T00:00:00.000,Adoption,NaN,Cat,Neutered Male,1 year,Domestic Shorthair,Black,Bagheera
7,A891034,2023-11-19T13:17:00.000,2023-11-19T13:17:00.000,2023-09-01T00:00:00.000,Adoption,NaN,Cat,Intact Female,2 months,Domestic Shorthair,Blue/White,NaN
8,A885692,2023-11-19T13:27:00.000,2023-11-19T13:27:00.000,2021-07-24T00:00:00.000,Adoption,NaN,Dog,Neutered Male,2 years,German Shepherd Mix,Black,Gunner
9,A888964,2023-11-19T14:07:00.000,2023-11-19T14:07:00.000,2022-09-15T00:00:00.000,Adoption,NaN,Dog,Spayed Female,1 year,Labrador Retriever,White/White,*Natalia
10,A862842,2023-11-19T14:14:00.000,2023-11-19T14:14:00.000,2022-06-01T00:00:00.000,Adoption,NaN,Dog,Neutered Male,1 year,Labrador Retriever Mix,Tan/Black,Cyprus
11,A881025,2023-11-19T14:28:00.000,2023-11-19T14:28:00.000,2017-06-17T00:00:00.000,Adoption,NaN,Dog,Spayed Female,6 years,Labrador Retriever,Black,*Morticia
12,A705625,2023-11-19T14:51:00.000,2023-11-19T14:51:00.000,2011-09-23T00:00:00.000,Return to Owner,NaN,Dog,Neutered Male,12 years,Pit Bull Mix,Brown/White,Jack
13,A892801,2023-11-19T15:02:00.000,2023-11-19T15:02:00.000,2023-05-10T00:00:00.000,Adoption,NaN,Cat,Intact Male,6 months,Domestic Shorthair,Brown Tabby,*Theodore
14,A853313,2023-11-19T16:14:00.000,2023-11-19T16:14:00.000,2017-03-16T00:00:00.000,Adoption,NaN,Dog,Spayed Female,6 years,American Staffordshire Terrier Mix,Chocolate/White,*Cocoa
15,A892123,2023-11-19T17:20:00.000,2023-11-19T17:20:00.000,2021-11-01T00:00:00.000,Adoption,NaN,Dog,Neutered Male,2 years,Labrador Retriever,Black,*Kravitz
16,A892121,2023-11-19T17:21:00.000,2023-11-19T17:21:00.000,2021-11-01T00:00:00.000,Adoption,NaN,Dog,Neutered Male,2 years,Labrador Retriever,Brown,*Crimson
17,A873013,2023-11-19T18:03:00.000,2023-11-19T18:03:00.000,2019-02-05T00:00:00.000,Adoption,NaN,Dog,Neutered Male,4 years,Pit Bull Mix,Black,*Cocoa Pebbles

In [ ]:
def extract(target_dir, target_file, start_date, execution_date):
    if execution_date == start_date:
        results = client.get("9t4d-g238", where="DateTime <= '{}'".format(start_date), limit=1000000)
    else:
        prior_execution_date = (datetime.datetime.strptime(execution_date, '%Y-%m-%d') - datetime.timedelta(days=1)).strftime('%Y-%m-%d')
        results = client.get("9t4d-g238", where="DateTime > '{}' AND DateTime <= '{}'".format(prior_execution_date, execution_date), limit=10000)
    pd.DataFrame(results).to_csv(target_file, index=False)

In [57]:
datetime.datetime.strptime('2019-05-08T18:20:00.000', '%Y-%m-%dT%H:%M:%S.%f')

datetime.datetime(2019, 5, 8, 18, 20)